[workspace]
members = ["crates/*"]

[workspace.dependencies]
bittorrent-peer-protocol = { path = "./crates/bittorrent-peer-protocol/" }
leechy-dht = { path = "./crates/leechy-dht" }
serde_bencode = { path = "./crates/serde_bencode" }
