[package]
name = "leechy-dht"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "^0.2.3"
anyhow = "^1.0.8"
tracing = "0.1.40"
rand = "0.8.5"
serde_bytes = "0.11.15"
